version: '3.8'

services:
  app:
    container_name: recipes-app
    environment:
      - POSTGRES_HOST=recipes-postgres
    build: .
    ports:
      - "12345:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - recipes-network

  postgres:
    container_name: recipes-postgres
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - recipes-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - recipes-network

volumes:
  recipes-data:

networks:
  recipes-network:
